site_name: Java Docs
theme:
  name: material
nav:
- helloworld:
  - HelloWorld: helloworld/HelloWorld.md
  - HelloWorldThree: helloworld/HelloWorldThree.md
  - HelloWorldTwo: helloworld/HelloWorldTwo.md
- search:
  - BinarySearch: search/BinarySearch.md
  - BinarySearchThree: search/BinarySearchThree.md
  - BinarySearchTwo: search/BinarySearchTwo.md
