site_name: Simply DSA
theme:
  name: material
  features:
  - navigation.sections
  - navigation.expand
  - toc.integrate
  - content.code.copy
nav:
- helloworld:
  - HelloWorld: helloworld/HelloWorld.md
- search:
  - BinarySearch: search/BinarySearch.md
